### ISSUE TITLE
OOB when match num is greater than 70

### ISSUE THREAD

**Issue by PIPIPIG233666** [TotsIsTots/573_Scouting_2023#1]
`PS C:\Users\pppig\Downloads\573_Scouting_2023-master> python .\match_scouting.py
pygame 2.3.0 (SDL 2.24.2, Python 3.11.2)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "C:\Users\pppig\Downloads\573_Scouting_2023-master\match_scouting.py", line 251, in <module>
    main()
  File "C:\Users\pppig\Downloads\573_Scouting_2023-master\match_scouting.py", line 102, in main
    team_number.options = matches[match_number.value - 1][team_color.value]
                          ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: list index out of range`

**Comment by TotsIsTots** [comment]
handled
